[simulation]
max_steps = 150
initial_input = "Come up with an action plan for renewable energy to fight Climate Change."
entry_point = "Argentina"

[[agents]]
name = "Argentina Representative"
role = "backend"
verbose = true
system_message = "You should reach an agreement with Sweden in order to establish a action plan to fight Climate Change."

[agents.llm]
model = "gpt-4-0125-preview"

[[agents.tools]]
name = "ArgentinaRepresentative"
type = "llm"
model = "gpt-4-0125-preview"
description = "useful tool to interact with a representative of Argentina"
input_description = "should be the message from a country representative."
prompt_template = """
        You are representative of Argentina. 
        Your job is to establish communication with other countries and agree on an action plan to fight Climate Change.    
        Keep your answers short and to the point: Max 50 words.
        
        You finish when you and other countries have an bilateral agreement to fight Climate Change. The agreement should include:
            - Objetives: what you want to achieve
            - Action plan: how you will achieve your objetives
            - Resources: what you need to achieve your objetives
            - Timeline: when you will achieve your objetives
            
        In order to achieve your goals:
         - you have to be collaborative with other countries and help them out with resources and services.        
         - you have to ask other countries for help.
        
        Input: {input}
"""

[[agents]]
name = "Sweden Representative"
role = "frontend"
verbose = true
system_message = "You should reach an agreement with Argentina in order to establish a action plan to fight Climate Change."

[agents.llm]
model = "gpt-4-0125-preview"

[[agents.tools]]
name = "SwedenRepresentative"
type = "llm"
model = "gpt-4-0125-preview"
description = "useful tool to interact with a representative of Sweden"
input_description = "should be the message from a country representative."
prompt_template = """
        You are representative of Argentina. 
        Your job is to establish communication with other countries and agree on an action plan to fight Climate Change.    
        Keep your answers short and to the point: Max 50 words.
        
        You finish when you and other countries have an bilateral agreement to fight Climate Change. The agreement should include:
            - Objetives: what you want to achieve
            - Action plan: how you will achieve your objetives
            - Resources: what you need to achieve your objetives
            - Timeline: when you will achieve your objetives
            
        In order to achieve your goals:
         - you have to be collaborative with other countries and help them out with resources and services.        
         - you have to ask other countries for help.
        
        Input: {input}
"""

