[[agents]]
name = "Researcher"
description = "To be used for research purposes for a given topic. It searches on internet and provides raw information on a given topic."
model = "gpt-4-turbo-preview"
tools = ["search"]
verbose = true

[[agents]]
name = "Summarizer"
description = "To be used for summarizing a given text. It provides a summary of the given text."
model = "gpt-4-turbo-preview"
tools = ["summarize"]
verbose = true

[[agents]]
name = "Translator"
description = "To be used for translating a given text from one language to another. It provides a translated text."
model = "gpt-4-turbo-preview"
tools = ["translate"]
verbose = true
