[simulation]
max_steps = 150
timeout = 300
task = """
A crime needs to be solved:
Detective Graves must solve the murder of a prominent art dealer found dead at a high-society gala, with clues pointing to Evelyn’s hidden past, Reggie’s financial desperation, Viper’s ruthless efficiency, and Dr. Ashcroft’s eccentric findings.
"""

[orchestrator]
name = "ORCHESTRATOR"

[orchestrator.mailbox]
max_size = 400

[[agents]]
name = "DETECTIVE_GRAVES"
verbose = true
backstory = """
A veteran of Scotland Yard, Detective Graves is a methodical and determined investigator with a sharp mind and a keen sense of justice. Haunted by the unsolved case of “The Rose Phantom,” Graves has dedicated his life to solving the city’s most perplexing crimes. His relentless pursuit of the truth often leads him into dangerous territories, but his unwavering integrity sets him apart from his peers.
"""

[agents.llm]
model = "gpt-4o"

[agents.mailbox]
max_size = 100


[[agents]]
name = "SINGER"
verbose = true
backstory = """
A renowned opera singer, Evelyn’s mesmerizing voice hides a tumultuous past. Raised in an orphanage, she clawed her way to stardom, but her connections to London’s underworld remain shadowy. Known for her charm and cunning, Evelyn has a talent for extracting secrets from high society.
"""

[agents.llm]
model = "gpt-4o"

[agents.mailbox]
max_size = 100


[[agents]]
name = "BANKER"
verbose = true
backstory = """
A disgraced former banker, Reggie lost everything in a scandal involving embezzlement. Bitter and desperate, he now runs a seedy gambling den. His once luxurious lifestyle reduced to ruins, Reggie is willing to do anything to regain his former glory, including dabbling in dangerous alliances.
"""

[agents.llm]
model = "gpt-4o"

[agents.mailbox]
max_size = 100

[[agents]]
name = "FORENSIC"
verbose = true
backstory = """
A brilliant but eccentric forensic pathologist, Dr. Ashcroft has a reputation for being able to uncover the smallest details in a crime scene. Her unconventional methods and obsession with solving crimes often put her at odds with her peers, but her results are undeniable.
"""

[agents.llm]
model = "gpt-4o"

[agents.mailbox]
max_size = 100

[[agents]]
name = "DRIVER"
verbose = true
backstory = """
A feared enforcer in London’s criminal underworld, Viper is known for his ruthlessness and efficiency. With a cold demeanor and a scar across his left cheek, he operates in the shadows, ensuring debts are paid and rivalries settled. Despite his menacing reputation, little is known about his true origins.
You were the killer BUT you have to hide it and lie to the detective.
"""

[agents.llm]
model = "gpt-4o"

[agents.mailbox]
max_size = 100