[logging]
file_path = "/Users/martin.dagostino/workspace/margostino/autobox/logs"
verbose = true

[simulation]
name = "Startup idea"
metrics_path = "/Users/martin.dagostino/workspace/margostino/autobox/metrics"
max_steps = 4
verbose = true
timeout = 300
task = "Brainstorm a startup idea, and come up with a name, target industry, a high level Business Model, and a tagline. Some ice-breaker questions: Climate Change, AGI, E-commerce, Travel, Books, Food, Music, Movies, Sports, Technology, Innovation, Harry Potter, Taylor Swift, Premier League, Star Wars."

[simulation.llm]
model = "gpt-4o-2024-08-06"

[evaluator]
name = "EVALUATOR"

[evaluator.mailbox]
max_size = 400

[evaluator.llm]
model = "gpt-4o-2024-08-06"

[orchestrator]
name = "ORCHESTRATOR"
instruction = "Ana and John need to decide a destiny for their summer vacation. They have to agree based on their preferences and constraints."

[orchestrator.mailbox]
max_size = 400

[orchestrator.llm]
model = "gpt-4o-2024-08-06"

[[agents]]
name = "ANA"
role = "Fullstack Software Engineer"
backstory = """
She is 35 and her passion is to solve problems. Lately she has been concerned about Climate Change. She has experience in LLM projects.
"""

[agents.llm]
model = "gpt-4o"

[agents.mailbox]
max_size = 100


[[agents]]
name = "JOHN"
role = "Senior Data Scientist"
backstory = """
He is 30 and his passion is to create new things. He is experienced in e-commerce industry. His is obsessed with AGI.
"""

[agents.llm]
model = "gpt-4o"

[agents.mailbox]
max_size = 100

[[agents]]
name = "JANE"
role = "Product Manager"
backstory = """
She like travelling, she is very smart when it comes to business. Her analytical mindset is very useful in decision making.
"""

[agents.llm]
model = "gpt-4o"

[agents.mailbox]
max_size = 100
