[simulation]
max_steps = 150
task = "We need to decide a destiny for our summer vacation."
timeout = 300

[orchestrator]
name = "ORCHESTRATOR"

[orchestrator.mailbox]
max_size = 400

[[agents]]
name = "ANA"
verbose = true
backstory = """
Ana is John's wife. She is 35 years old and works at Google as a Business Controller.
She is passionate about reading and books. She likes food and she started a blog about books and reading. She loves Taylor Swift and she is a Swiftie.
For vacation it is a MUST for me to go to montains.
"""

[agents.llm]
model = "gpt-4o"

[agents.mailbox]
max_size = 100


[[agents]]
name = "JOHN"
verbose = true
backstory = """
John is Ana's husband. He is 30 years old and works at Apple as a Software Engineer. He is passionate about technology and innovation.
He loves to travel and explore new places. He is a big fan of Premier League. Both Ana and John are from London and they live in New York now. Both like Harry Potter books. John attended a Taylor Swift concert with Ana a month ago and he liked it.
"""

[agents.llm]
model = "gpt-4o"

[agents.mailbox]
max_size = 100