from autobox.api.get_simulations import handle_get_simulations
from autobox.transformations.project_simulations_to_response import transform


async def handle_get_projects():
    simulations = await handle_get_simulations()
    project_simulations = transform(simulations)

    return {
        "projects": [
            {
                "id": "1",
                "name": "Friends Dynamics",
                "description": "Experiment to understand how friends influence each other on decision making",
                "status": "active",
                "simulations": [
                    *project_simulations,
                    {
                        "id": "friends-dynamics-2",
                        "name": "Weekend Planning",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-07-20T10:00:00",
                        "finished_at": "2024-07-20T10:30:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "friends-dynamics-3",
                        "name": "Gym Buddy Motivation",
                        "status": "timeout",
                        "progress": 70,
                        "started_at": "2024-08-01T18:00:00",
                        "finished_at": "2024-08-01T18:40:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "friends-dynamics-4",
                        "name": "Birthday Gift Selection",
                        "status": "aborted",
                        "progress": 20,
                        "started_at": "2024-08-10T09:00:00",
                        "finished_at": None,
                        "aborted_at": "2024-08-10T09:10:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "2",
                "name": "Work Dynamics",
                "description": "Experiment to understand how work environment influences productivity",
                "status": "active",
                "simulations": [
                    {
                        "id": "work-1",
                        "name": "Monday Blues Productivity",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-01-03T09:00:00",
                        "finished_at": "2024-01-03T17:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "work-2",
                        "name": "Teamwork vs. Individual Performance",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-02-10T09:00:00",
                        "finished_at": "2024-02-10T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "3",
                "name": "Workplace Collaboration",
                "description": "A simulation to analyze how teams collaborate and how leadership dynamics affect productivity and decision-making.",
                "status": "active",
                "simulations": [
                    {
                        "id": "collab-1",
                        "name": "Leadership and Decision-Making Speed",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-03-05T10:00:00",
                        "finished_at": "2024-03-05T16:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "collab-2",
                        "name": "Team Cohesion Under Pressure",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-03-15T12:00:00",
                        "finished_at": "2024-03-15T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "4",
                "name": "Climate Change Strategy",
                "description": "A simulation where different regions must decide on environmental policies, balancing economic growth with sustainability efforts.",
                "status": "active",
                "simulations": [
                    {
                        "id": "climate-1",
                        "name": "Green Energy Adoption Rates",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-04-20T08:00:00",
                        "finished_at": "2024-04-20T14:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "climate-2",
                        "name": "Carbon Tax Impact on Industry",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-04-28T08:00:00",
                        "finished_at": "2024-04-28T15:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "5",
                "name": "Marketing Campaign Effectiveness",
                "description": "Simulate the impact of various marketing strategies on consumer behavior, focusing on how social media influencers or advertisements affect purchase decisions.",
                "status": "active",
                "simulations": [
                    {
                        "id": "marketing-1",
                        "name": "Influencer vs. Traditional Ads",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-05-10T10:00:00",
                        "finished_at": "2024-05-10T15:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "marketing-2",
                        "name": "Seasonal Campaign Effectiveness",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-06-01T12:00:00",
                        "finished_at": "2024-06-01T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "6",
                "name": "Political Negotiation",
                "description": "A simulation of political negotiations where different parties must reach consensus on policy issues. It focuses on how compromises and alliances are formed.",
                "status": "active",
                "simulations": [
                    {
                        "id": "politics-1",
                        "name": "Coalition Building and Policy Trade-offs",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-06-15T09:00:00",
                        "finished_at": "2024-06-15T14:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "politics-2",
                        "name": "Diplomatic Resolution Tactics",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-07-05T11:00:00",
                        "finished_at": "2024-07-05T16:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "7",
                "name": "Resource Allocation in Crises",
                "description": "A simulation for understanding decision-making in resource distribution during emergencies, such as natural disasters or pandemics.",
                "status": "active",
                "simulations": [
                    {
                        "id": "crises-1",
                        "name": "Medical Supplies During a Pandemic",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-08-01T10:00:00",
                        "finished_at": "2024-08-01T16:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "crises-2",
                        "name": "Food Distribution After a Natural Disaster",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-08-15T09:00:00",
                        "finished_at": "2024-08-15T17:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "8",
                "name": "Startup Decision Making",
                "description": "Simulate the decision-making process in startups, focusing on funding, product launches, and market entry strategies.",
                "status": "active",
                "simulations": [
                    {
                        "id": "startup-1",
                        "name": "Product Launch Timing",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-09-10T11:00:00",
                        "finished_at": "2024-09-10T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "startup-2",
                        "name": "Funding Strategy for Series A",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-09-25T12:00:00",
                        "finished_at": "2024-09-25T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "9",
                "name": "Family Dynamics",
                "description": "Experiment with how family members influence each other when making major decisions, like financial planning, career choices, or home buying.",
                "status": "active",
                "simulations": [
                    {
                        "id": "family-1",
                        "name": "Financial Planning for Retirement",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-10-05T10:00:00",
                        "finished_at": "2024-10-05T16:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "family-2",
                        "name": "Career Choice Impact on Family Stability",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-10-12T09:00:00",
                        "finished_at": "2024-10-12T17:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "10",
                "name": "Healthcare Policy Analysis",
                "description": "A simulation to analyze the impact of different healthcare policies on public health outcomes, focusing on access, quality, and cost.",
                "status": "active",
                "simulations": [
                    {
                        "id": "healthcare-1",
                        "name": "Universal Healthcare vs. Private Insurance",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-10-01T10:00:00",
                        "finished_at": "2024-10-01T16:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "healthcare-2",
                        "name": "Impact of Preventive Care Policies",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-10-15T10:00:00",
                        "finished_at": "2024-10-15T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "11",
                "name": "Employee Training and Development",
                "description": "A simulation to design and evaluate employee training programs, focusing on skills development, performance improvement, and career advancement.",
                "status": "active",
                "simulations": [
                    {
                        "id": "training-1",
                        "name": "Leadership Development for New Managers",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-10-01T09:00:00",
                        "finished_at": "2024-10-01T17:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "training-2",
                        "name": "Technical Skill Growth Through Workshops",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-10-10T10:00:00",
                        "finished_at": "2024-10-10T16:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "12",
                "name": "Social Influence Network",
                "description": "Simulate how opinions and behaviors spread through a social network, exploring how individuals change their views based on peer pressure, authority figures, or media.",
                "status": "active",
                "simulations": [
                    {
                        "id": "social-1",
                        "name": "Peer Pressure and Opinion Shifts",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-10-20T11:00:00",
                        "finished_at": "2024-10-20T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "social-2",
                        "name": "Media Influence on Public Opinion",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-01-05T09:00:00",
                        "finished_at": "2024-01-05T16:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "13",
                "name": "Crowd Behavior in Emergencies",
                "description": "Study how people react and make decisions in high-stress environments, such as evacuations or natural disasters, focusing on cooperation vs. self-preservation.",
                "status": "active",
                "simulations": [
                    {
                        "id": "crowd-1",
                        "name": "Evacuation During a Fire",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-01-15T09:00:00",
                        "finished_at": "2024-01-15T17:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "crowd-2",
                        "name": "Flood Evacuation Behavior",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-02-01T10:00:00",
                        "finished_at": "2024-02-01T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "14",
                "name": "Group Decision-Making",
                "description": "A simulation where a team must make collective decisions under time pressure, testing how leadership, persuasion, and group dynamics influence outcomes.",
                "status": "active",
                "simulations": [
                    {
                        "id": "group-1",
                        "name": "Consensus Building Under Time Pressure",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-02-10T11:00:00",
                        "finished_at": "2024-02-10T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "group-2",
                        "name": "Leadership Persuasion Techniques",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-02-25T10:00:00",
                        "finished_at": "2024-02-25T17:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "15",
                "name": "Consumer Buying Behavior",
                "description": "Analyze how individuals make purchasing decisions when exposed to different marketing tactics, peer recommendations, or brand loyalty factors.",
                "status": "active",
                "simulations": [
                    {
                        "id": "consumer-1",
                        "name": "Effect of Social Media Ads on Buying",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-03-05T09:00:00",
                        "finished_at": "2024-03-05T17:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "consumer-2",
                        "name": "Brand Loyalty vs. Peer Recommendations",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-03-20T10:00:00",
                        "finished_at": "2024-03-20T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "16",
                "name": "Conflict Resolution",
                "description": "Simulate a scenario where two or more parties must resolve a conflict, exploring negotiation tactics, compromise, and power dynamics.",
                "status": "active",
                "simulations": [
                    {
                        "id": "conflict-1",
                        "name": "Negotiation Tactics in Business Conflicts",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-04-05T10:00:00",
                        "finished_at": "2024-04-05T17:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "conflict-2",
                        "name": "Compromise Strategies in Diplomacy",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-04-20T11:00:00",
                        "finished_at": "2024-04-20T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "17",
                "name": "Digital Addiction",
                "description": "Explore how individuals interact with technology, focusing on behaviors around app usage, social media engagement, and strategies to break addictive patterns.",
                "status": "active",
                "simulations": [
                    {
                        "id": "digital-1",
                        "name": "Screen Time Reduction Strategies",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-05-05T09:00:00",
                        "finished_at": "2024-05-05T16:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "digital-2",
                        "name": "Impact of App Notifications on Focus",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-05-15T10:00:00",
                        "finished_at": "2024-05-15T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "digital-3",
                        "name": "Breaking Social Media Addiction",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-05-25T11:00:00",
                        "finished_at": "2024-05-25T17:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "18",
                "name": "Cultural Adaptation",
                "description": "Simulate how individuals adapt when moving to a new culture, studying behaviors around conformity, language learning, and social integration.",
                "status": "active",
                "simulations": [
                    {
                        "id": "culture-1",
                        "name": "Language Learning and Social Integration",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-06-01T10:00:00",
                        "finished_at": "2024-06-01T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "culture-2",
                        "name": "Cultural Shock and Adaptation Phases",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-06-10T09:00:00",
                        "finished_at": "2024-06-10T17:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "culture-3",
                        "name": "Building Relationships in a New Culture",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-06-20T12:00:00",
                        "finished_at": "2024-06-20T19:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
            {
                "id": "19",
                "name": "Work-Life Balance",
                "description": "Investigate how people manage their personal and professional lives, making decisions that affect their productivity, happiness, and health.",
                "status": "active",
                "simulations": [
                    {
                        "id": "balance-1",
                        "name": "Managing Workload to Prevent Burnout",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-07-01T09:00:00",
                        "finished_at": "2024-07-01T17:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "balance-2",
                        "name": "Balancing Family Time with Work Commitments",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-07-10T08:00:00",
                        "finished_at": "2024-07-10T16:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                    {
                        "id": "balance-3",
                        "name": "Time Management Techniques for Work-Life Harmony",
                        "status": "completed",
                        "progress": 100,
                        "started_at": "2024-07-20T10:00:00",
                        "finished_at": "2024-07-20T18:00:00",
                        "internal_dashboard_url": None,
                        "public_dashboard_url": None,
                    },
                ],
            },
        ]
    }
